[package]
name = "fs-server"
author = "Yellow Jacket Space Program"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2"
anyhow = "1.0"
argon2 = "0.4"
base64 = "0.13"
rand = "0.8"
rusqlite = "0.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.23", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.2", features = ["v4"] }
