[package]
name = "servo"
authors = ["Jeff Shelton"]
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2"
anyhow = "1.0"
argon2 = "0.4"
base64 = "0.13"
env_logger = "0.10"
log = "0.4"
rand = "0.8"
rusqlite = { version = "0.28", features = ["bundled", "functions"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.23", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.2", features = ["v4"] }

[[bin]]
name = "servo"
