[package]
name = "fs-server"
author = "Yellow Jacket Space Program"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2"
anyhow = "1.0"
argon2 = "0.4"
base64 = "0.13"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
rand = "0.8"
rusqlite = "0.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.2", features = ["v4"] }
