[package]
name = "servo"
authors = ["Jeff Shelton"]
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.6"
actix-web = "4.2"
anyhow = "1.0"
base64 = "0.13"
env_logger = "0.10"
fs-protobuf-rust = { git = "ssh://git@github-research.gatech.edu/YJSP/fs-protobuf-rust" }
log = "0.4"
quick-protobuf = "0.8"
rand = "0.8"
rusqlite = { version = "0.28", features = ["bundled", "functions"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.23", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.2", features = ["v4"] }
clap = "4.4.6"
once_cell = "1.18.0"
dns-lookup = "2.0.4"
ssh2 = "0.9.4"

[[bin]]
name = "servo"
